---
- name: Generate configuration files
  template: src=router.j2 dest=/home/cgnetng/ANSIBLE/CFGS/{{item.hostname}}.txt
  with_items: "{{ test_routers }}"
  #  - { hostname: rtr01-10hy }
  #  - { hostname: rtr02-10hy }
